# Generated by Django 5.0.6 on 2024-06-08 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="date_upload",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="document",
            name="sous_categorie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enseignement", "Enseignement"),
                    ("exercices", "Exercices"),
                    ("examen_blanc", "Examen Blanc"),
                    ("intervenants", "Intervenants"),
                    ("ressources", "Ressources"),
                    ("foad", "FOAD"),
                    ("dossier_pro", "Dossier Professionnel"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("administrative", "Administrative"),
                    ("pedagogique", "Pédagogique"),
                ],
                max_length=20,
            ),
        ),
    ]
