# Generated by Django 5.0.6 on 2024-06-08 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_date_upload_document_sous_categorie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="date_upload",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
